name: back_in_black
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/
  
  fonts:
    - family: SofiaPro
      fonts:
        - asset: lib/fonts/sofia-pro-regular.ttf
        - asset: lib/fonts/sofia-pro-regular-italic.ttf
          style: italic
        - asset: lib/fonts/sofia-pro-ultra-light.ttf
          weight: 100
        - asset: lib/fonts/sofia-pro-ultra-light-italic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/sofia-pro-extra-light.ttf
          weight: 200
        - asset: lib/fonts/sofia-pro-extra-light-italic.ttf
          weight: 200
          style: italic
        - asset: lib/fonts/sofia-pro-light.ttf
          weight: 300
        - asset: lib/fonts/sofia-pro-light-italic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/sofia-pro-regular.ttf
          weight: 400
        - asset: lib/fonts/sofia-pro-regular-italic.ttf
          weight: 400
          style: italic
        - asset: lib/fonts/sofia-pro-medium.ttf
          weight: 500
        - asset: lib/fonts/sofia-pro-medium-italic.ttf
          weight: 500
          style: italic
        - asset: lib/fonts/sofia-pro-semi-bold.ttf
          weight: 600
        - asset: lib/fonts/sofia-pro-semi-bold-italic.ttf
          weight: 600
          style: italic
        - asset: lib/fonts/sofia-pro-bold.ttf
          weight: 700
        - asset: lib/fonts/sofia-pro-bold-italic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/sofia-pro-black.ttf
          weight: 900
        - asset: lib/fonts/sofia-pro-black-italic.ttf
          weight: 900
          style: italic
