name: acdc_weather_app
description: "AC/DC's dark weather forecast"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #System Features
  auto_injector: ^2.0.4

  #Cache
  shared_preferences: ^2.2.3

  #HTTP requests
  dio: ^5.4.3+1

  #Packages
  back_in_black:
    path: ../back_in_black

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  mocktail: ^1.0.3

flutter:

  uses-material-design: true

 